name: cppcheck-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyse:
    name: Run Cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'recursive'
    - name: Run Cppcheck
      uses: deep5050/cppcheck-action@3.0
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: output