name: cppcheck-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyse:
    name: Run Cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'recursive'
    - name: Run Cppcheck
      uses: Bedzior/cppcheck-action@v1.0.0
      with:
        enabled checks: all
        enable inconclusive: true
        generate report: true
        path: src
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: output