name: cppcheck-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
          
    - name: Run Cppcheck
      uses: Bedzior/cppcheck-action@v1.0
      with:
        enabled checks: all
        enable inconclusive: true
        generate report: true
		
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: output