name: Linux - Build and Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dependencies - Linux
      run: sudo apt-get install -y libsndfile1-dev && sudo apt-get install -y libpulse-dev && sudo apt-get install -y libasound2-dev

    - name: Compile - Linux
      run: cd src/ && make linux-pulse
      
    - name: Unit Tests - Linux
      run: cd src/ && export PATH=$PATH:$(pwd) && cd test/ && python test.py
